### ISSUE TITLE
Add CMAF

### ISSUE THREAD

**Issue by PhilippeR** [robert-will-brown/video-streaming-cheatsheet#15]
Common Media Application Format or CMAF is a format for packaging and delivering various forms of HTTP-based media. CMAF is itself not a protocol but rather a container and set of standards for single-approach video streaming that works with protocols like HLS and MPEG-DASH

**Comment by robert-will-brown** [comment]
Thanks @PhilippeR, added with some editing to fit the two page limit and merged in #17.
